### ISSUE TITLE
本机docker安装的ES7.3版本 一直链接失败

### ISSUE THREAD

**Issue by fengyikang88** [1340691923/ElasticView#10]
提示：Get "http://127.0.0.1:9200/": dial tcp 127.0.0.1:9200: connect: connection refused

但是我用ES-head5和postman都可以连接上

**Comment by 1340691923** [comment]
请问您是docker方式启动的吗

**Comment by 1340691923** [comment]
请问您是docker方式启动的elasticview吗
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1340691923/ElasticView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 下午5:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[1340691923/ElasticView] 本机docker安装的ES7.3版本 一直链接失败 (Issue #10)





 
提示：Get "http://127.0.0.1:9200/": dial tcp 127.0.0.1:9200: connect: connection refused
 
但是我用ES-head5和postman都可以连接上

**Comment by 1340691923** [comment]
请问您是docker方式启动的elasticview吗

**Comment by fengyikang88** [comment]
是的 docker方式启动的

下面是我docker版本的：
{
  "name" : "40b80f85eed6",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "jYVYOVp4RgGQXqa0YtAxoA",
  "version" : {
    "number" : "7.3.0",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "de777fa",
    "build_date" : "2019-07-24T18:30:11.767338Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by 1340691923** [comment]
那么你得用容器外访问宿主机的方式访问&nbsp; 具体方式在 https://www.jianshu.com/p/7cb866d005a5



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] 本机docker安装的ES7.3版本 一直链接失败 (Issue #10)




 
是的 docker方式启动的
 
下面是我docker版本的：
 {
 "name" : "40b80f85eed6",
 "cluster_name" : "docker-cluster",
 "cluster_uuid" : "jYVYOVp4RgGQXqa0YtAxoA",
 "version" : {
 "number" : "7.3.0",
 "build_flavor" : "default",
 "build_type" : "docker",
 "build_hash" : "de777fa",
 "build_date" : "2019-07-24T18:30:11.767338Z",
 "build_snapshot" : false,
 "lucene_version" : "8.1.0",
 "minimum_wire_compatibility_version" : "6.8.0",
 "minimum_index_compatibility_version" : "6.0.0-beta1"
 },
 "tagline" : "You Know, for Search"
 }

**Comment by fengyikang88** [comment]
好的 我试试

**Comment by 1340691923** [comment]
在readme的应用程序 下载 那里

**Comment by 1340691923** [comment]
下载地址 https://gitee.com/cynthia520/elastic-view/releases/

**Comment by fengyikang88** [comment]
好的 谢谢

**Comment by 1340691923** [comment]
请问解决了您的问题吗，如已解决请关闭该issue

**Comment by 1340691923** [comment]
或者你也可以下载发布的包里的二进制，解压后直接执行



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 晚上6:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] 本机docker安装的ES7.3版本 一直链接失败 (Issue #10)




 
是的 docker方式启动的
 
下面是我docker版本的：
 {
 "name" : "40b80f85eed6",
 "cluster_name" : "docker-cluster",
 "cluster_uuid" : "jYVYOVp4RgGQXqa0YtAxoA",
 "version" : {
 "number" : "7.3.0",
 "build_flavor" : "default",
 "build_type" : "docker",
 "build_hash" : "de777fa",
 "build_date" : "2019-07-24T18:30:11.767338Z",
 "build_snapshot" : false,
 "lucene_version" : "8.1.0",
 "minimum_wire_compatibility_version" : "6.8.0",
 "minimum_index_compatibility_version" : "6.0.0-beta1"
 },
 "tagline" : "You Know, for Search"
 }
