### ISSUE TITLE
密码怎么是明文显示

### ISSUE THREAD

**Issue by yanming-zhang** [1340691923/ElasticView#12]
密码怎么是全明文显示，感觉这样不太安全

![image](https://user-images.githubusercontent.com/11608532/168125780-53487093-3479-4e83-ab04-acdda6ad72ed.png)

**Comment by 1340691923** [comment]
您好，我将于下个版本更新密码加密保存在数据库功能



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月13日(周五) 凌晨0:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 密码怎么是明文显示 (Issue #12)




 
密码怎么是全明文显示，感觉这样不太安全

**Comment by 1340691923** [comment]
您好，我已更新es密码加密保存功能，加密方式是AES，密钥为配置文件中esPwdSecret字段，可将配置文件dbType改为mysql，查看eslink表中密码字段验证，如没问题请关闭该issue



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月13日(周五) 凌晨0:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 密码怎么是明文显示 (Issue #12)




 
密码怎么是全明文显示，感觉这样不太安全

**Comment by PotatoCloud** [comment]
**请求添加敏感信息隐藏功能**
