### ISSUE TITLE
Docker重启容器如何保持数据不丢失

### ISSUE THREAD

**Issue by SoloHuang** [1340691923/ElasticView#13]
请问Docker安装方式，在界面配置的连接配置，如何能再重启后能保持一致

**Comment by PotatoCloud** [comment]
maybe u create a new docker container every time?😅

**Comment by SoloHuang** [comment]
似乎不是，docker container stop ,docker container start 后数据依然没了。可能启动时脚本覆盖了。

**Comment by hooklee2000** [comment]
我看了docker的脚本，需要修过sql，数据库存在就不再重新创建。要保留mysql数据和log文件，可以有两种方式：
1、需要传递宿主机文件夹到容器，运行docker run -v $PWD/ElasticView/mysql:/ /var/lib/mysql -v $PWD/ElasticView/log:/usr/local/ElasticView/log 
2、或者提交docker 容器，下次保留配置。docker commit

**Comment by PotatoCloud** [comment]
> 我看了docker的脚本，需要修改sql，数据库存在就不再重新创建。如create database if not exist ，create table if not exist 。 要保留mysql数据和log文件，可以有两种方式： 1、需要传递宿主机文件夹到容器，运行 mkdir -p $PWD/ElasticView/mysql mkdir -p $PWD/ElasticView/logs docker run -v $PWD/ElasticView/mysql:/var/lib/mysql -v $PWD/ElasticView/logs:/usr/local/logs 2、或者提交docker 容器，下次保留配置。docker commit

I noticed this problem, I made a pull request to **1340691923**, this might solve the problem

**Comment by hooklee2000** [comment]
Good job！

**Comment by PotatoCloud** [comment]
if I solve ur problem, please close this issue :)🍻🍻

**Comment by SoloHuang** [comment]
thanks！不过镜像还没更新。

**Comment by PotatoCloud** [comment]
> thanks！不过镜像还没更新。

**u should contact** @1340691923

**Comment by 1340691923** [comment]
@SoloHuang 您好，我已更新最新docker镜像文件，请重新拉取一下
