### ISSUE TITLE
数据抽取功能

### ISSUE THREAD

**Issue by kecikeci** [1340691923/ElasticView#15]
试用了下，功能挺好的，很赞！

就是缺少使用文档，导致在数据抽取功能那，配置抽取任务时，新增映射那卡住了，不会操作。
如果有个给索引编辑字段的功能就好了，类似数据库的编辑表结构

![image](https://user-images.githubusercontent.com/32811349/169061838-f2acc5a3-0a32-4bb3-9f82-fcd8222f0b2a.png)

**Comment by 1340691923** [comment]
文档这段正在整理，请持续关注官网：http://www.elastic-view.cn




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1340691923/ElasticView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月18日(星期三) 晚上10:11
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[1340691923/ElasticView] 数据抽取功能 (Issue #15)





 
试用了下，功能挺好的，很赞！
 
就是缺少使用文档，导致在数据抽取功能那，配置抽取任务时，新增映射那卡住了，不会操作。
 如果有个给索引编辑字段的功能就好了，类似数据库的编辑表结构
