### ISSUE TITLE
数据库不能持久化

### ISSUE THREAD

**Issue by kecikeci** [1340691923/ElasticView#18]
使用最新镜像，试了mysql，sqlite3，都不能持久化。
![image](https://user-images.githubusercontent.com/32811349/169506087-5b9c28f9-dbe3-42ed-801a-1526ea9aa9ee.png)
![image](https://user-images.githubusercontent.com/32811349/169506138-9928074a-762f-4592-a3c8-a1d3cd22848c.png)
文件已挂载到宿主机

![image](https://user-images.githubusercontent.com/32811349/169506293-12d97e34-4577-40da-8565-1e1229d48788.png)

我看好像是有个db_init.lock，不知道是不是这个控制的。如果是，建议放到目录里，这样可以挂载到宿主机来解决

**Comment by 1340691923** [comment]
请问持久化是指您是遇到了重启容器，数据丢失的问题吗

**Comment by 1340691923** [comment]
请加一下qq群持续关注进展

**Comment by kecikeci** [comment]
> 请问持久化是指您是遇到了重启容器，数据丢失的问题吗

是的，重启后会重新执行sql脚本，导致数据丢失

已申请入群

**Comment by kecikeci** [comment]
新版docker镜像已支持数据持久化

https://github.com/1340691923/ElasticView#docker部署
