### ISSUE TITLE
登录密码错误

### ISSUE THREAD

**Issue by congyin** [1340691923/ElasticView#2]

**Comment by 1340691923** [comment]
请问您的问题解决了吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月21日(周一) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [1340691923/ElasticView] 登录密码错误 (Issue #2)




 
Closed #2.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by congyin** [comment]
解决了，我是用mysql5.6, 运行es_view.sql 文件时，无法创建gm_user表，使用mysql5.7可以创建并使用admin登录
