### ISSUE TITLE
秘钥长度错误, 当前传入长度为 44

### ISSUE THREAD

**Issue by ironbang** [1340691923/ElasticView#21]
【连接树管理】-->【新建连接信息】中的密码是啥？我填的elastic密码，给我报错【秘钥长度错误, 当前传入长度为 44】，可是我的密码才10位，这个44哪里来的？

**Comment by 1340691923** [comment]
config.json 中的esPwdSecret的长度必须为 32

**Comment by 1340691923** [comment]
请检查一下esPwdSecret字段的长度

**Comment by ironbang** [comment]
esPwdSecret这个字段填es的密码吗？

**Comment by 1340691923** [comment]
因为es密码是需要加密，所以这个配置项是aes加密密钥



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月27日(周五) 下午5:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] 秘钥长度错误, 当前传入长度为 44 (Issue #21)




 
esPwdSecret这个字段填es的密码吗？

**Comment by ironbang** [comment]
那我怎么用我的明文密码进行aes加密呢？我用在线的aes加密出来都是44位

**Comment by ironbang** [comment]
我知道了

**Comment by 1340691923** [comment]
请加一下qq群，支持一下我们，谢谢🙏
