### ISSUE TITLE
没看到哪里自持https访问es的

### ISSUE THREAD

**Issue by guowei3758** [1340691923/ElasticView#23]

**Comment by 1340691923** [comment]
直接在连接树设置https://ip 不可以吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月30日(周四) 中午11:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 没看到哪里自持https访问es的 (Issue #23)

**Comment by guowei3758** [comment]
> 直接在连接树设置https://ip 不可以吗
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月30日(周四) 中午11:21 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [1340691923/ElasticView] 没看到哪里自持https访问es的 (Issue #23) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

哦哦，我知道了，https协议应该是可以的，但是我还搞了证书，应该是不能做证书的认证

**Comment by 1340691923** [comment]
最新版本支持证书链接，目前还没来的及发包到github，可以加群获得
