### ISSUE TITLE
cannot unmarshal object into Go struct field SearchHits.hits.total of type int64

### ISSUE THREAD

**Issue by afumu** [1340691923/ElasticView#24]
使用docker的es，连接查询数据有问题
es版本：7.17.0

查询的时候，报以下错误

![image](https://user-images.githubusercontent.com/50908453/176837322-924814de-7596-4cd9-8885-ea5251c41247.png)

**Comment by 1340691923** [comment]
连接树管理里，版本设置成了6，改成7就可以了



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 1, 2022 14:31 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [1340691923/ElasticView] cannot unmarshal object into Go struct fieldSearchHits.hits.total of type int64 (Issue #24)




 
使用docker的es，连接查询数据有问题
 es版本：7.17.0
 
查询的时候，报以下错误
