### ISSUE TITLE
建议开发工具增加原生http请求

### ISSUE THREAD

**Issue by 565784135** [1340691923/ElasticView#27]
例如 GET  IP:9200/test/_mapping

目前在 ElasticView 报错
在 elasticsearch-head 正常

![image](https://user-images.githubusercontent.com/24539345/182281009-bec4da0d-9840-44d9-af25-fc3e5a194812.png)

**Comment by 1340691923** [comment]
把请求body里的{} 去掉就可以了



---原始邮件---
发件人: "Memory ***@***.***&gt;
发送时间: 2022年8月2日(周二) 上午10:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 建议开发工具增加原生http请求 (Issue #27)




 
例如 GET  IP:9200/test/_mapping
 
目前在 ElasticView 报错
 在 elasticsearch-head 正常
