### ISSUE TITLE
"秘钥长度错误, 当前传入长度为 17

### ISSUE THREAD

**Issue by 25280841** [1340691923/ElasticView#29]
https: //  
测试正确，点击确认时弹出这个错误， 无法保存 连接信息

response/Response.go:99	Error	{"err": ["秘钥长度错误, 当前传入长度为 17", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/api/EsLinkController.go,行数:79,函数名:github.com/1340691923/ElasticView/api.EsLinkController.InsertAction", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go,行数:132,函数名:github.com/gofiber/fiber/v2.(*App).next", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go,行数:792,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/middleware/Rbac.go,行数:33,函数名:github.com/1340691923/ElasticView/middleware.Rbac", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/middleware/jwt.go,行数:51,函数名:github.com/1340691923/ElasticView/middleware.JwtMiddleware", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/middleware/Time.go,行数:16,函数名:github.com/1340691923/ElasticView/middleware.Timer", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go,行数:132,函数名:github.com/gofiber/fiber/v2.(*App).next", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go,行数:792,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/middleware/filesystem/filesystem.go,行数:111,函数名:github.com/gofiber/fiber/v2/middleware/filesystem.New.func1", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/middleware/compress/compress.go,行数:54,函数名:github.com/gofiber/fiber/v2/middleware/compress.New.func3", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/middleware/cors/cors.go,行数:141,函数名:github.com/gofiber/fiber/v2/middleware/cors.New.func1", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go,行数:132,函数名:github.com/gofiber/fiber/v2.(*App).next", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/gofiber/fiber/v2@v2.27.0/router.go,行数:160,函数名:github.com/gofiber/fiber/v2.(*App).handler", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/server.go,行数:2328,函数名:github.com/valyala/fasthttp.(*Server).serveConn", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go,行数:223,函数名:github.com/valyala/fasthttp.(*workerPool).workerFunc", "文件名:C:/Users/Administrator/go/pkg/mod/github.com/valyala/fasthttp@v1.33.0/workerpool.go,行数:195,函数名:github.com/valyala/fasthttp.(*workerPool).getCh.func1"]}

**Comment by 1340691923** [comment]
密钥长度必须为32，你把配置文件里的esPwdSecret改成32位就好了



---原始邮件---
发件人: "Tang ***@***.***&gt;
发送时间: 2022年8月5日(周五) 晚上11:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] "秘钥长度错误, 当前传入长度为 17 (Issue #29)




 
https: //
 测试正确，点击确认时弹出这个错误， 无法保存 连接信息
 
response/Response.go:99Error{"err": ["秘钥长度错误, 当前传入长度为 17", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/api/EsLinkController.go,行数:79,函数名:github.com/1340691923/ElasticView/api.EsLinkController.InsertAction", ***@***.***/router.go,行数:132,函数名:github.com/gofiber/fiber/v2.(*App).next", ***@***.***/ctx.go,行数:792,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/middleware/Rbac.go,行数:33,函数名:github.com/1340691923/ElasticView/middleware.Rbac", ***@***.***/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/middleware/jwt.go,行数:51,函数名:github.com/1340691923/ElasticView/middleware.JwtMiddleware", ***@***.***/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", "文件名:D:/CodeApply/WORK/JAVA/ElasticView/middleware/Time.go,行数:16,函数名:github.com/1340691923/ElasticView/middleware.Timer", ***@***.***/router.go,行数:132,函数名:github.com/gofiber/fiber/v2.(*App).next", ***@***.***/ctx.go,行数:792,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", ***@***.***/middleware/filesystem/filesystem.go,行数:111,函数名:github.com/gofiber/fiber/v2/middleware/filesystem.New.func1", ***@***.***/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", ***@***.***/middleware/compress/compress.go,行数:54,函数名:github.com/gofiber/fiber/v2/middleware/compress.New.func3", ***@***.***/ctx.go,行数:789,函数名:github.com/gofiber/fiber/v2.(*Ctx).Next", ***@***.***/middleware/cors/cors.go,行数:141,函数名:github.com/gofiber/fiber/v2/middleware/cors.New.func1", ***@***.***/router.go,行数:132,函数名:github.com/gofiber/fiber/v2.(*App).next", ***@***.***/router.go,行数:160,函数名:github.com/gofiber/fiber/v2.(*App).handler", ***@***.***/server.go,行数:2328,函数名:github.com/valyala/fasthttp.(*Server).serveConn", ***@***.***/workerpool.go,行数:223,函数名:github.com/valyala/fasthttp.(*workerPool).workerFunc", ***@***.***/workerpool.go,行数:195,函数名:github.com/valyala/fasthttp.(*workerPool).getCh.func1"]}

**Comment by 25280841** [comment]
> 密钥长度必须为32，你把配置文件里的esPwdSecret改成32位就好了

能用了，多谢，没看到有这个要求

**Comment by 1340691923** [comment]
抱歉，是我没写清楚



---原始邮件---
发件人: "Tang ***@***.***&gt;
发送时间: 2022年8月6日(周六) 凌晨0:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] "秘钥长度错误, 当前传入长度为 17 (Issue #29)




  
密钥长度必须为32，你把配置文件里的esPwdSecret改成32位就好了
  
能用了，多谢，没看到有这个要求
