### ISSUE TITLE
有docker部署的么

### ISSUE THREAD

**Issue by aiaiduo** [1340691923/ElasticView#3]
有docker 部署的么？

**Comment by 1340691923** [comment]
您好，我已接收到您的建议，我将于下周完成docker版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月19日(周六) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 有docker部署的么 (Issue #3)




 
有docker 部署的么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1340691923** [comment]
您好，我已完成docker部署的工作，请在readme查看部署方式

**Comment by 1340691923** [comment]
如果没有问题，我将关闭该issue

**Comment by jaxwang** [comment]
关闭吧

**Comment by aiaiduo** [comment]
> 您好，我已完成docker部署的工作，请在readme查看部署方式

收到，多谢！
