### ISSUE TITLE
建议navicat能支持中文显示

### ISSUE THREAD

**Issue by atuxp** [1340691923/ElasticView#34]
建议navicat能支持中文显示

**Comment by 1340691923** [comment]
请问是哪些功能点需要中文显示

**Comment by atuxp** [comment]
就是文档里面含有中文的话，显示出来的是unicode编码
![1](https://user-images.githubusercontent.com/7660375/193237876-b7c16418-a6ea-4d52-b774-154eae855ad1.jpg)

**Comment by KnightNUI** [comment]
> 就是文档里面含有中文的话，显示出来的是unicode编码 ![1](https://user-images.githubusercontent.com/7660375/193237876-b7c16418-a6ea-4d52-b774-154eae855ad1.jpg)

你这个是存进去就是unicode吧，我这边查看ES里中文数据没有问题，展示的是中文

**Comment by atuxp** [comment]
> > 就是文档里面含有中文的话，显示出来的是unicode编码 ![1](https://user-images.githubusercontent.com/7660375/193237876-b7c16418-a6ea-4d52-b774-154eae855ad1.jpg)
> 
> 你这个是存进去就是unicode吧，我这边查看ES里中文数据没有问题，展示的是中文

确实是，存进去之前用htmlspecialchars转了一下:(  但也可以搜到。直接存就没问题了。。。
