### ISSUE TITLE
配置数据库使用mysql后报错failed to create new symlink

### ISSUE THREAD

**Issue by ziyekudeng** [1340691923/ElasticView#36]
![image](https://user-images.githubusercontent.com/42562723/191642010-355c82fa-90fb-4312-8e5b-05cac250f178.png)

**Comment by 1340691923** [comment]
报的错是创建软连接失败，问题不大



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月22日(周四) 上午10:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 配置数据库使用mysql后报错failed to create new symlink (Issue #36)
