### ISSUE TITLE
切换Navicat和其它菜单标签时,会导致左侧菜单打开或关闭

### ISSUE THREAD

**Issue by panda-student** [1340691923/ElasticView#37]
![image](https://user-images.githubusercontent.com/71381346/191889625-4624cef0-0701-4f82-816a-c28b20ac7dab.png)
比如现在是左侧菜单是打开状态,只要从其它任意标签切换回Navicat标签,左侧菜单就会关闭,当左侧菜单关闭时,切换到Navicat标签就会打开菜单,如下图
![image](https://user-images.githubusercontent.com/71381346/191889774-8ab28870-79fd-4feb-9002-d70481381ec1.png)

**Comment by 1340691923** [comment]
最新版本已经修复，还没有来的及传包到github，可以加群获取
