### ISSUE TITLE
下面给的官网打不开，是需要翻墙嘛

### ISSUE THREAD

**Issue by nudityfa** [1340691923/ElasticView#38]

**Comment by 1340691923** [comment]
开源不易，服务器没钱续费过期了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月29日(周四) 晚上9:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 下面给的官网打不开，是需要翻墙嘛 (Issue #38)

**Comment by 1340691923** [comment]
官网恢复了
