### ISSUE TITLE
既然有人维护, 我就来提issue了, 先来一波, 跟用户权限相关的问题. 

### ISSUE THREAD

**Issue by jaxwang** [1340691923/ElasticView#4]
### 比较影响使用的几个问题:
- 增加的自定义角色, 就算这个角色给了全部权限.  该角色下的用户也无法登陆. 查看了一下网络请求, 发现有接口500. 下面会放图.
- 新增用户后, 密码在用户列表以密码密文形式显示, 可能是考虑安全性, 但是在编辑用户的时候,  密码文本框依然显示密码密文, 如果这个时候保存, 比如我修改了真实姓名,  密码会被二次修改, 导致用户无法登陆....
- 新增用户时, 明明选择了对应的角色 , 但是新增后系统弹出的toast提示中显示的用户角色是 undefined, 我觉得这个可能是引起用户无法登陆的根本原因. 

**我的部署环境是`macOS Big Sur 11.6`, 数据库是 `mariadb 10.6.4` , 部署的程序是`ElasticViewMac`**

### 问题截图:

![](https://s3.bmp.ovh/imgs/2022/03/be24114bff1c6888.png)

___
![](https://s3.bmp.ovh/imgs/2022/03/ed07980cce8df015.png)
___

![](https://s3.bmp.ovh/imgs/2022/03/701c474adca6dde4.png)

___
![](https://s3.bmp.ovh/imgs/2022/03/aae6f5f62597efd5.png)
___
![](https://s3.bmp.ovh/imgs/2022/03/542b9a8c4cbc7d67.png)
___

后续使用中有其他问题再持续反馈,  传图不易,  辛苦大神帮忙优化下.

**Comment by 1340691923** [comment]
已修复完成，请下载最新的二进制文件替换，如已解决问题，请关闭该issue

**Comment by jaxwang** [comment]
> 已修复完成，请下载最新的二进制文件替换，如已解决问题，请关闭该issue

我用最新版本的二进制文件替换了,  但是添加的用户指定自定义角色后,  依然没有办法登录 
报错的api为:  /api/gm_user/info
http status code: 500
return message :  runtime error: invalid memory address or nil pointer dereference

**Comment by 1340691923** [comment]
请问是下载的图中的这个吗?
![企业微信截图_16479405298872](https://user-images.githubusercontent.com/38397940/159447108-efca364e-7d89-4bb1-8eef-9137305f927e.png)

**Comment by 1340691923** [comment]
请确认旧进程是否已经杀掉了

**Comment by 1340691923** [comment]
kill掉之前的进程 ，再运行新下载的二进制文件

**Comment by 1340691923** [comment]
期待您的答复

**Comment by 1340691923** [comment]
您好，请问杀掉旧进程了吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月22日(周二) 下午4:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] 既然有人维护, 我就来提issue了, 先来一波, 跟用户权限相关的问题.  (Issue #4)




  
已修复完成，请下载最新的二进制文件替换，如已解决问题，请关闭该issue
  
我用最新版本的二进制文件替换了,  但是添加的用户指定自定义角色后,  依然没有办法登录
 报错的api为:  /api/gm_user/info
 http status code: 500
 return message :  runtime error: invalid memory address or nil pointer dereference

**Comment by jaxwang** [comment]
抱歉, 刚看到 已经搞定了  感谢~

**Comment by jaxwang** [comment]
> 抱歉, 刚看到 已经搞定了 感谢~

确实是没有杀掉进程的原因, 是我疏忽了
