### ISSUE TITLE
Navicat 查询时字段报错

### ISSUE THREAD

**Issue by DraperHXY** [1340691923/ElasticView#48]
![image](https://user-images.githubusercontent.com/18048426/231734465-d2ab820e-0616-4c21-9c01-7505bd43039e.png)

**Comment by 1340691923** [comment]
es连接那里版本号选错了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月13日(周四) 晚上6:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] Navicat 查询时字段报错 (Issue #48)
