### ISSUE TITLE
首页数据统计看板"索引所占空间大小"这一项的数据显示有问题.

### ISSUE THREAD

**Issue by jaxwang** [1340691923/ElasticView#5]
每次刷新后得到的数据可能会不一致, 时而1G  时而2G  有时则显示197G . 

![](https://i.bmp.ovh/imgs/2022/03/ceceefe482182152.png)

____

![](https://s3.bmp.ovh/imgs/2022/03/9bbe7f5ff938811a.png)

____

**ElasticViewMac v1.4**

**Comment by 1340691923** [comment]
我才应该感谢你才是，感谢你帮我提issue，帮我找bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月23日(周三) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 首页数据统计看板"索引所占空间大小"这一项的数据显示有问题. (Issue #5)




 
每次刷新后得到的数据可能会不一致, 时而1G  时而2G  有时则显示197G .
 

 
 

 
 
ElasticViewMac v1.4

**Comment by 1340691923** [comment]
等我不忙了就来看这个问题，暂时猜测是页面卡了，因为数据显示这里有一个数字递增动画效果



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月23日(周三) 下午4:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 首页数据统计看板"索引所占空间大小"这一项的数据显示有问题. (Issue #5)




 
每次刷新后得到的数据可能会不一致, 时而1G  时而2G  有时则显示197G .
 

 
 

 
 
ElasticViewMac v1.4

**Comment by 1340691923** [comment]
可以加个qq吗

**Comment by 1340691923** [comment]
1340691923

**Comment by 1340691923** [comment]
请问最新版本解决了您的问题吗
