### ISSUE TITLE
Navicat 查看数据的功能, 索引库搜索后的列表点击查看数据, 数据显示为其他索引库的数据, 而非选择的索引库

### ISSUE THREAD

**Issue by jaxwang** [1340691923/ElasticView#6]
- Navicat 查看数据的功能, 索引库搜索后的列表点击查看数据, 数据显示为其他索引库的数据, 而非选择的索引库
- 如果不用搜索功能, 点击索引展示的数据是正确的, 一旦搜索关键字后, 点击搜索结果中的索引名, 右侧显示的数据就错了. 应该是关联关系错乱了. 
- 这个bug有点严重, 会导致用户操作错误的索引库.

____

![](https://i.bmp.ovh/imgs/2022/03/eef6df1f5eee6135.png)

____

![](https://i.bmp.ovh/imgs/2022/03/3c46f66164de5696.png)

_____

**ElasticViewMac v1.4**

**Comment by 1340691923** [comment]
您好，我已修复该bug，并由于不可抗力因素，暂已将下载地址转移至gitee，请访问&nbsp;&nbsp;https://gitee.com/cynthia520/elastic-view/releases/ ，若已修复完成，请关闭该issue



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月23日(周三) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] Navicat 查看数据的功能, 索引库搜索后的列表点击查看数据, 数据显示为其他索引库的数据, 而非选择的索引库 (Issue #6)




  
Navicat 查看数据的功能, 索引库搜索后的列表点击查看数据, 数据显示为其他索引库的数据, 而非选择的索引库 

如果不用搜索功能, 点击索引展示的数据是正确的, 一旦搜索关键字后, 点击搜索结果中的索引名, 左侧显示的数据就错了. 应该是关联关系错乱了. 

这个bug有点严重, 会导致用户操作错误的索引库. 
 
 

 
 

 
 
ElasticViewMac v1.4

**Comment by 1340691923** [comment]
多谢帮我提issue，有新的想法也可以给我提



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月23日(周三) 下午4:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] Navicat 查看数据的功能, 索引库搜索后的列表点击查看数据, 数据显示为其他索引库的数据, 而非选择的索引库 (Issue #6)




  
Navicat 查看数据的功能, 索引库搜索后的列表点击查看数据, 数据显示为其他索引库的数据, 而非选择的索引库 

如果不用搜索功能, 点击索引展示的数据是正确的, 一旦搜索关键字后, 点击搜索结果中的索引名, 左侧显示的数据就错了. 应该是关联关系错乱了. 

这个bug有点严重, 会导致用户操作错误的索引库. 
 
 

 
 

 
 
ElasticViewMac v1.4
