### ISSUE TITLE
docker-hub 上是两年前的镜像

### ISSUE THREAD

**Issue by ScalaFirst** [1340691923/ElasticView#64]
请问有新的稳定版本么？

**Comment by 1340691923** [comment]
有的，请加微信号：qq1340691923



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月16日(周三) 上午9:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] docker-hub 上是两年前的镜像 (Issue #64)




 
请问有新的稳定版本么？

**Comment by 1340691923** [comment]
也可以加一下qq群 685549060
