### ISSUE TITLE
first path segment in URL cannot contain colon 测试连接报错

### ISSUE THREAD

**Issue by verydemo** [1340691923/ElasticView#7]
测试连接报错

**Comment by 1340691923** [comment]
请截图给我，以及es版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 中午1:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] first path segment in URL cannot contain colon 测试连接报错 (Issue #7)




 
测试连接报错

**Comment by 1340691923** [comment]
根据报错信息分析，应该是es连接信息那里 没有加http或者https



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 中午1:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] first path segment in URL cannot contain colon 测试连接报错 (Issue #7)




 
测试连接报错

**Comment by 1340691923** [comment]
请问解决了您的问题吗
