### ISSUE TITLE
本地启动报错

### ISSUE THREAD

**Issue by lwxk** [1340691923/ElasticView#8]
![image](https://user-images.githubusercontent.com/32501171/162101641-d07ca800-0bbb-47b4-84ad-0fe01c0e1491.png)
也有可能我哪里配置没有配？
另外其他页面怎么切换连接源？默认都是local的

**Comment by 1340691923** [comment]
您好，在连接数管理里添加连接，添加好后再右上角的下拉选框内选择连接即可，图片中报错是9200端口没有开启

**Comment by 1340691923** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1340691923/ElasticView"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月7日(星期四) 上午9:26
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[1340691923/ElasticView] 本地启动报错 (Issue #8)





 

 也有可能我哪里配置没有配？
 另外其他页面怎么切换连接源？默认都是local的

**Comment by 1340691923** [comment]
![企业微信截图_16492950716092](https://user-images.githubusercontent.com/38397940/162102582-0a59202a-85be-45c0-aec5-52112b2b08b7.png)

**Comment by 1340691923** [comment]
![企业微信截图_16492951157789](https://user-images.githubusercontent.com/38397940/162102608-3614563d-18c6-4bd1-bebd-41bfc48d54b0.png)

**Comment by 1340691923** [comment]
![企业微信截图_16492951586](https://user-images.githubusercontent.com/38397940/162102620-c5c046bb-31e3-4f36-92f4-81e8338cc369.png)

**Comment by 1340691923** [comment]
如果解决问题，请关闭issue

**Comment by lwxk** [comment]
> 您好，在连接数管理里添加连接，添加好后再右上角的下拉选框内选择连接即可，图片中报错是9200端口没有开启

![image](https://user-images.githubusercontent.com/32501171/162113249-06ecc2cc-ab41-4e9f-9e12-bfe1bbc40daa.png)
直接能访问，应该是开启了吧？

**Comment by 1340691923** [comment]
请问是如何解决的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 中午11:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] 本地启动报错 (Issue #8)




  
您好，在连接数管理里添加连接，添加好后再右上角的下拉选框内选择连接即可，图片中报错是9200端口没有开启
  

 直接能访问，应该是开启了吧？

**Comment by lwxk** [comment]
> 请问是如何解决的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年4月7日(周四) 中午11:17 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [1340691923/ElasticView] 本地启动报错 (Issue #8) 您好，在连接数管理里添加连接，添加好后再右上角的下拉选框内选择连接即可，图片中报错是9200端口没有开启 直接能访问，应该是开启了吧？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

没有解决啊，就本地启动了，elasticview连不上。

**Comment by 1340691923** [comment]
![image](https://user-images.githubusercontent.com/38397940/162132730-58d30d0d-a400-4079-97c3-23c8cfbcaa21.png)

**Comment by 1340691923** [comment]
因为我在您的另一个issue里看到连接上了

**Comment by lwxk** [comment]
> 因为我在您的另一个issue里看到连接上了

这是我连的线上环境的。

**Comment by lwxk** [comment]
> 因为我在您的另一个issue里看到连接上了

抱歉，打扰了，我知道了，可能是我用的WSL，不能用localhost或者127.0.0.1

**Comment by 1340691923** [comment]
那为什么es head可以连



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 下午2:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [1340691923/ElasticView] 本地启动报错 (Issue #8)




  
因为我在您的另一个issue里看到连接上了
  
抱歉，打扰了，我知道了，可能是我用的WSL，不能用localhost或者127.0.0.1
