### ISSUE TITLE
布局是否可以调整下，给查询结果更多空间？

### ISSUE THREAD

**Issue by lwxk** [1340691923/ElasticView#9]
![image](https://user-images.githubusercontent.com/32501171/162113513-a7b810e5-94c5-41f5-948d-c61673be7c74.png)

**Comment by 1340691923** [comment]
可以的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 布局是否可以调整下，给查询结果更多空间？ (Issue #9)

**Comment by 1340691923** [comment]
下一版本发布会改一下排版



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月7日(周四) 中午11:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [1340691923/ElasticView] 布局是否可以调整下，给查询结果更多空间？ (Issue #9)

**Comment by 1340691923** [comment]
请查看一下最新版本是否已解决问题
